# Generated by Django 5.2.6 on 2025-10-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.TextField(),
        ),
    ]
