# Generated by Django 5.2.6 on 2025-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
